package GUI;

import assets.lookandfeel.Colores;
import assets.objects.Comunes;
import java.awt.CardLayout;
import vistas.*;

/**
 * Panel contenedor para las diferentes vistas de la interfaz.
 * Cuenta con un CardLayout para mostrar cada una de ellas.
 * @author José Francisco Blasco Jiménez
 */
public class Container extends javax.swing.JPanel {
    private CardLayout card;
    private Interfaz frame;
    private Menu menu;
    private Comunes comunes;

    /**
     * Crea una nueva instancia.
     */
    public Container() {
        initComponents();
        card = (CardLayout) getLayout();
        anadeVistasALayout();
        card.show(this, "home");
    }    
    
    /**
     * Setea los objetos comunes para toda la interfaz
     * @param com Objeto del tipo Comunes a asignar.
     */
    public void setComunes(Comunes com) {
        comunes = com;
        setFrame(comunes.getPARENT());
    }

    /**
     * Devuelve el objeto Comunes asignado a esta instancia.
     * @return Objeto de tipo Comunes asignado al objeto en cuestión.
     */
    public Comunes getComunes() {
        return comunes;
    }
    
    /**
     * Devuelve el CardLayout del objeto.
     * @return Objeto CardLayout de dicha instancia.
     */
    public CardLayout getCard() {
        return card;
    }

    /**
     * Signa un menú al objeto para podérselo pasar a las vistas que lo necesiten.
     * @param menu Menú para asignar al objeto.
     */
    public void setMenu(Menu menu) {
        this.menu = menu;
    }

    /**
     * Devuelve el menú asignado al objeto.
     * @return Menú asignado a esta instancia.
     */
    public Menu getMenu() {
        return menu;
    }
    
    /**
     * Añado todas las vistas del contenedor al CardLayout para poderlas mostrar.
     */
    private void anadeVistasALayout() {
        card.addLayoutComponent(artNuevo, "artNuevo");
        card.addLayoutComponent(artList, "artList");
        card.addLayoutComponent(artResul, "artResul");
        card.addLayoutComponent(evtNuevo, "evtNuevo");
        card.addLayoutComponent(evtList, "evtList");
        card.addLayoutComponent(evtResul, "evtResul");
        card.addLayoutComponent(tecNuevo, "tecNuevo");
        card.addLayoutComponent(tecList, "tecList");
        card.addLayoutComponent(tecResul, "tecResul");
        card.addLayoutComponent(home, "home");        
    }
    
    /**
     * Setea el CardLayout a las vistas que lo necesiten.
     */
    public void setChildrenLayout() {
        artList.setCard(card);
        artResul.setCard(card);
        evtList.setCard(card);
        evtResul.setCard(card);
        tecList.setCard(card);
    }
    
    /**
     * Setea esta instancia como contenedor de las vistas.
     */
    public void setChildrenContainer() {
        home.setContainer(this);
        evtNuevo.setContainer(this);
        evtList.setContainer(this);
        evtResul.setContainer(this);
        artNuevo.setContainer(this);
        artList.setContainer(this);
        artResul.setContainer(this);
        tecNuevo.setContainer(this);
        tecList.setContainer(this);
        tecResul.setContainer(this);
    }

    public ArtistasResultado getArtResul() {
        return artResul;
    }

    public EventosResultado getEvtResul() {
        return evtResul;
    }

    public TecnicosResultado getTecResul() {
        return tecResul;
    }

    /**
     * Setea el objeto Interfaz pasado por parámetro como Frame (contenedor del contenedor).
     * @param frame Formulario Interfaz para asignar al contenedor.
     */
    public void setFrame(Interfaz frame) {
        this.frame = frame;
    }

    /**
     * Devuelve el Objeto de tipo Interfaz asignado a esta instancia.
     * @return Interfaz asignada al objeto.
     */
    public Interfaz getFrame() {
        return frame;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        artList = new vistas.ArtistasListado();
        artNuevo = new vistas.ArtistasNuevo();
        artResul = new vistas.ArtistasResultado();
        evtList = new vistas.EventosListado();
        evtNuevo = new vistas.EventosNuevo();
        home = new vistas.Home();
        tecNuevo = new vistas.TecnicosNuevo();
        tecResul = new vistas.TecnicosResultado();
        tecList = new vistas.TecnicosListado();
        evtResul = new vistas.EventosResultado();

        setBackground(Colores.TRANSPARENTE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new java.awt.CardLayout());

        artList.setMinimumSize(new java.awt.Dimension(800, 600));
        add(artList, "card2");

        artNuevo.setMinimumSize(new java.awt.Dimension(800, 600));
        add(artNuevo, "card3");

        artResul.setMinimumSize(new java.awt.Dimension(800, 600));
        add(artResul, "card4");

        evtList.setMinimumSize(new java.awt.Dimension(800, 600));
        add(evtList, "card5");

        evtNuevo.setMinimumSize(new java.awt.Dimension(800, 600));
        add(evtNuevo, "card6");

        home.setMinimumSize(new java.awt.Dimension(800, 600));
        home.setPreferredSize(new java.awt.Dimension(800, 600));
        add(home, "card8");

        tecNuevo.setMinimumSize(new java.awt.Dimension(800, 600));
        add(tecNuevo, "card10");
        add(tecResul, "card11");
        add(tecList, "card11");
        add(evtResul, "card7");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private vistas.ArtistasListado artList;
    private vistas.ArtistasNuevo artNuevo;
    private vistas.ArtistasResultado artResul;
    private vistas.EventosListado evtList;
    private vistas.EventosNuevo evtNuevo;
    private vistas.EventosResultado evtResul;
    private vistas.Home home;
    private vistas.TecnicosListado tecList;
    private vistas.TecnicosNuevo tecNuevo;
    private vistas.TecnicosResultado tecResul;
    // End of variables declaration//GEN-END:variables
}
