package GUI;

import assets.lookandfeel.Colores;
import assets.objects.Comunes;
import java.awt.*;
import java.util.ArrayList;
import javax.swing.JFrame;

/**
 * Interfaz de la aplicación. Hereda de JFrame.
 *
 * @author José Francisco Blasco Jiménez
 */
public class Interfaz extends javax.swing.JFrame {

    private ArrayList<Component> camposActualizarEventos;
    private ArrayList<Component> camposActualizarArtistas;
    private ArrayList<Component> camposActualizarTecnicos;
    private Comunes comunes;
    int x, y;
    private CardLayout card;

    /**
     * Crea una nueva instancia.
     */
    public Interfaz() {
        setUndecorated(true);
        comunes = new Comunes(this);
        initComponents();
        camposActualizarEventos = new ArrayList();
        camposActualizarArtistas = new ArrayList();
        camposActualizarTecnicos = new ArrayList();
        setLocationRelativeTo(null);
        card = (CardLayout) container.getLayout();
        container.setComunes(comunes);
        container.setMenu(menu);
        container.setChildrenLayout();
        container.setChildrenContainer();
        menu.setContainer(container);
    }
    
    /**
     * Setea el título de la ventana. Sobreescribe el mismo método de la
     * superclase (JFrame). Añade "The Basement - " a la cadena pasada por parámetro
     *
     * @param titulo Cadena a concatenar para formar el título.
     */
    @Override
    public void setTitle(String titulo) {
        super.setTitle("The Basement - " + titulo);
        lblBasement.setText(getTitle());
        pnlMain.setBackground(Colores.NARANJA);
        pnlMain.setBackground(Colores.AZUL);
    }

    /**
     * Devuelve la lista de campos a actualizar cada vez que se realiza una
     * operación CRUD en la colección de eventos.
     *
     * @return Campos afectados por las operaciones de eventos.
     */
    public ArrayList<Component> getCamposActualizarEventos() {
        return camposActualizarEventos;
    }

    /**
     * Devuelve la lista de campos a actualizar cada vez que se realiza una
     * operación CRUD en la colección de artistas.
     *
     * @return Campos afectados por las operaciones de artistas.
     */
    public ArrayList<Component> getCamposActualizarArtistas() {
        return camposActualizarArtistas;
    }

    /**
     * Devuelve la lista de campos a actualizar cada vez que se realiza una
     * operación CRUD en la colección de técnicos.
     *
     * @return Campos afectados por las operaciones de técnicos.
     */
    public ArrayList<Component> getCamposActualizarTecnicos() {
        return camposActualizarTecnicos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new components.atoms.RoundPanel();
        contenedor = new components.atoms.RoundPanel();
        menu = new GUI.Menu();
        container = new GUI.Container();
        pnlTitulo = new javax.swing.JPanel();
        lblBasement = new components.atoms.Label();
        pnlSalirMinimizar = new javax.swing.JPanel();
        lblExit = new javax.swing.JLabel();
        lblMinimize = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(Colores.TRANSPARENTE);
        setSize(new java.awt.Dimension(1024, 641));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });

        pnlMain.setBackground(Colores.AZUL);
        pnlMain.setPreferredSize(new java.awt.Dimension(1024, 641));
        pnlMain.setRoundBottomLeft(99);
        pnlMain.setRoundBottomRight(99);
        pnlMain.setRoundTopLeft(99);
        pnlMain.setRoundTopRight(99);

        contenedor.setBackground(Colores.TRANSPARENTE);
        contenedor.setRoundBottomLeft(99);
        contenedor.setRoundBottomRight(99);
        contenedor.setRoundTopLeft(99);
        contenedor.setRoundTopRight(99);
        contenedor.setLayout(new java.awt.BorderLayout());
        contenedor.add(menu, java.awt.BorderLayout.LINE_START);
        contenedor.add(container, java.awt.BorderLayout.CENTER);

        pnlTitulo.setBackground(Colores.TRANSPARENTE);

        lblBasement.setForeground(Colores.BLANCO);
        lblBasement.setText("The Basement - Home");

        javax.swing.GroupLayout pnlTituloLayout = new javax.swing.GroupLayout(pnlTitulo);
        pnlTitulo.setLayout(pnlTituloLayout);
        pnlTituloLayout.setHorizontalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBasement, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        pnlTituloLayout.setVerticalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBasement, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
        );

        pnlSalirMinimizar.setBackground(Colores.TRANSPARENTE);

        lblExit.setIcon(new javax.swing.ImageIcon("E:\\TFG\\Redimension\\assets\\icons\\ExitBlanco.png")); // NOI18N
        lblExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
        });

        lblMinimize.setIcon(new javax.swing.ImageIcon("E:\\TFG\\Redimension\\assets\\icons\\MinimizeBlanco.png")); // NOI18N
        lblMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlSalirMinimizarLayout = new javax.swing.GroupLayout(pnlSalirMinimizar);
        pnlSalirMinimizar.setLayout(pnlSalirMinimizarLayout);
        pnlSalirMinimizarLayout.setHorizontalGroup(
            pnlSalirMinimizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSalirMinimizarLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(lblMinimize)
                .addGap(16, 16, 16)
                .addComponent(lblExit)
                .addContainerGap())
        );
        pnlSalirMinimizarLayout.setVerticalGroup(
            pnlSalirMinimizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSalirMinimizarLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(pnlSalirMinimizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlSalirMinimizarLayout.createSequentialGroup()
                        .addGap(0, 10, Short.MAX_VALUE)
                        .addComponent(lblMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(pnlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 469, Short.MAX_VALUE)
                .addComponent(pnlSalirMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlSalirMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Se llama a este método cuando se presiona el mouse dentro del componente.
     * Actualiza las coordenadas x e y con la posición del evento.
     *
     * @param evt Evento del mouse que desencadena el método.
     */
    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_formMousePressed

    /**
     * Este método se llama cuando se arrastra el mouse dentro del componente.
     * Obtiene la posición actual del puntero del mouse y ajusta la ubicación
     * del componente para que se mueva de acuerdo al arrastre. Además,
     * establece el cursor del componente como el cursor de movimiento y cambia
     * el fondo del panel principal al color naranja.
     *
     * @param evt El evento del mouse que desencadena el método.
     */
    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        Point p = MouseInfo.getPointerInfo().getLocation();
        setLocation(p.x - x, p.y - y);
        setCursor(new Cursor(Cursor.MOVE_CURSOR));
        pnlMain.setBackground(Colores.NARANJA);
    }//GEN-LAST:event_formMouseDragged

    /**
     * Se ejecuta cuando se suelta el mouse dentro del componente.
     * Restaura el cursor predeterminado del componente y cambia el fondo del
     * panel principal al color azul.
     *
     * @param evt El evento del mouse que desencadena el método.
     */
    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        pnlMain.setBackground(Colores.AZUL);
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_formMouseReleased

    /**
     * Cuando se pulsa el mobotón de minimizar, se minimiza la ventana.
     * @param evt Evento de ratón que desencadena el método.
     */
    private void lblMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseClicked
        setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_lblMinimizeMouseClicked

    /**
     * Cuando se pulsa el botón de cerrar ventana, se sale de la aplciación.
     * @param evt Evento de ratón
     */
    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblExitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.Container container;
    private components.atoms.RoundPanel contenedor;
    private components.atoms.Label lblBasement;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblMinimize;
    private GUI.Menu menu;
    private components.atoms.RoundPanel pnlMain;
    private javax.swing.JPanel pnlSalirMinimizar;
    private javax.swing.JPanel pnlTitulo;
    // End of variables declaration//GEN-END:variables

    
}
