package components.organisms.keypads;

import DAO.DAOEvento;
import DAO.DAOArtista;
import DAO.DAOTecnico;
import GUI.Interfaz;
import GUI.Modal;
import POJOs.Evento;
import assets.lookandfeel.Botones;
import assets.lookandfeel.Colores;
import assets.objects.Comunes;
import components.organisms.tables.TblListado;
import java.util.ArrayList;
import java.util.HashMap;
import assets.resources.Operaciones;

/**
 * Botonera para la vista de listado.
 * @author José Francisco Blasco Jiménez
 */
public class KeyListado extends javax.swing.JPanel {
    private DAOEvento dEv;
    private DAOArtista dArt;
    private DAOTecnico dTec;
    private int tipo;
    private TblListado tabla;
    private Interfaz parent;
    private Modal modal;
    
    /**
     * Crea una nueva instancia.
     */
    public KeyListado() {
        initComponents();
    }
    
    /**
     * Setea los objetos comunes.
     * @param comunes Objeto de tipo Comunes a asignar.
     */
    public void setComunes(Comunes comunes) {
        dEv = comunes.getDAOEV();
        dArt = comunes.getDAOART();
        dTec = comunes.getDAOTEC();
        modal = comunes.getMODAL();
    }
    
    /**
     * Setea la tabla con la que va a trabajar la botonera.
     * @param tabla Tabla a asignar.
     */
    public void setTabla(TblListado tabla) {
        this.tabla = tabla;
        tipo = tabla.getTipo();
    }

    /**
     * Asgina una ventana para tomar de referencia al mostrar los mensajes.
     * @param parent Ventana a asignar.
     */
    public void setParent(Interfaz parent) {
        this.parent = parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEliminar = new components.atoms.ImgButton();

        setBackground(Colores.TRANSPARENTE);

        btnEliminar.setBackground(Colores.TRANSPARENTE);
        btnEliminar.setIcon(Botones.ELIMINAR_NARANJA);
        btnEliminar.setTipo(Botones.BTN_ELIM_NARANJA);
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Elimina la entidadd según el tipo
     * @param evt Evento de ratón.
     */
    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        HashMap<String, Integer> ids = tabla.getSelected();
        boolean eliminadosTodos = true;
        ArrayList<String> noEliminados  = new ArrayList();
        String entidad = null, msg = null;
        
        switch (tipo) {
            case Comunes.TIPO_EVENTO:
                entidad = "evento";
                eliminadosTodos = eliminaEventos(ids, noEliminados);
                break;
            case Comunes.TIPO_ARTISTA:
                entidad = "artista";
                eliminadosTodos = eliminaArtistas(ids, noEliminados);
                break;
            case Comunes.TIPO_TECNICO:
                entidad = "técnico";
                eliminadosTodos = eliminaTecnicos(ids, noEliminados);
                break;
        }
        
        msg = devuelveMensaje(noEliminados, ids, entidad, eliminadosTodos);
        modal.setTipo(Modal.MODAL_OK);modal.setText(msg);
        modal.setOpciones(false);
    }//GEN-LAST:event_btnEliminarMouseClicked

    /**
     * Devuelve el mensaje en función de lo sucedido al eliminar la entidad
     * @param noEliminados Lista a la que se han añadido los elementos no eliminados, en caso de que existan.
     * @param ids Mapa con los identificadores de los elementos seleccionados y sus índices correspondientes.
     * @param entidad Cadena con el tipo de entidad, para poder mostrarlo en el mensaje.
     * @param eliminadosTodos Indica si se han podido o no eliminar todos los elementos.
     * @return 
     */
    private String devuelveMensaje(ArrayList<String> noEliminados, HashMap<String, Integer> ids,
            String entidad, boolean eliminadosTodos) {
        String msg = null;
        if (noEliminados.size() == 0) {
            if (ids.size() == 1) {
                msg = "El " + entidad + "ha sido eliminado.";
            }
        } else {
            if (eliminadosTodos)
                msg = "Todos los " + entidad + "s eliminados.";
            else {
                if (noEliminados.size() == ids.size())
                    msg = "Ninguno de los " + entidad + "s n se pudo eliminar.";
                else
                    msg = "Algún " + entidad + " no se pudo eliminar.";
            }
        }
        return msg;
    }

    /**
     * Elimina los eventos seleccionados
     * @param ids Pares clave-valor con los ids y su índice.
     * @param noEliminados Lista para añadir los eventos no eliminados, si los hay.
     * @return True si se han podido eliminar todos los elementos. False en caso contrario.
     */
    private boolean eliminaEventos(HashMap<String, Integer> ids, ArrayList<String> noEliminados) {
        boolean eliminadosTodos =true;
        ArrayList<Evento> lista;
        
        for (String id : ids.keySet()) {
            if (dEv.borrar(id))
                tabla.getModel().removeRow(ids.get(id));
            else {
                noEliminados.add(id);
                eliminadosTodos = false;
            }
        }
        return eliminadosTodos;                
    }

    /**
     * Elimina los artistas seleccionados
     * @param ids Pares clave-valor con los ids y su índice.
     * @param noEliminados Lista para añadir los eventos no eliminados, si los hay.
     * @return True si se han podido eliminar todos los elementos. False en caso contrario.
     */
    private boolean eliminaArtistas(HashMap<String, Integer> ids, ArrayList<String> noEliminados) {
        boolean eliminadosTodos = true;
        int indAnterior = Integer.MAX_VALUE, ind;
        for (String id : ids.keySet()) {
            ind = ids.get(id);
            if (dArt.borrar(id)) {
                if (ind > indAnterior)
                    ind = ind -1;
                tabla.getModel().removeRow(ids.get(id));
            } else {
                noEliminados.add(id);
                eliminadosTodos = false;
            }
        }
        
        Operaciones.actualizaDatos(parent.getCamposActualizarTecnicos());
        
        return eliminadosTodos;                
    }

    /**
     * Elimina los técnicos seleccionados
     * @param ids Pares clave-valor con los ids y su índice.
     * @param noEliminados Lista para añadir los eventos no eliminados, si los hay.
     * @return True si se han podido eliminar todos los elementos. False en caso contrario.
     */
    private boolean eliminaTecnicos(HashMap<String, Integer> ids, ArrayList<String> noEliminados) {
        boolean eliminadosTodos =true;
        for (String id : ids.keySet()) {
            if (dTec.borrar(id))
                tabla.getModel().removeRow(ids.get(id));
            else {
                noEliminados.add(id);
                eliminadosTodos = false;
            }
        }
        
        Operaciones.actualizaDatos(parent.getCamposActualizarTecnicos());
        
        return eliminadosTodos;                
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private components.atoms.ImgButton btnEliminar;
    // End of variables declaration//GEN-END:variables
}
