package components.organisms.keypads;

import POJOs.*;
import assets.lookandfeel.Botones;
import assets.objects.Comunes;
import components.organisms.tables.TblRider;
import DAO.*;
import GUI.Interfaz;
import GUI.Modal;
import assets.lookandfeel.Colores;
import java.awt.Component;
import java.util.*;
import assets.resources.Operaciones;

/**
 * Botonera para las vistas de adición.
 * @author José Francisco Blasco Jiménez
 */
public class KeyNuevo extends javax.swing.JPanel {
    private DAOEvento dEv;
    private DAOArtista dArt;
    private DAOTecnico dTec;
    private HashMap<String, Component> campos;
    private int tipo;
    private TblRider tabla;
    private Interfaz parent;
    private Modal modal;
    
    /**
     * Crea una nueva instancia.
     */
    public KeyNuevo() {
        initComponents();
        
    }

    /**
     * Setea los objetos comunes.
     * @param comunes Objeto de tipo Comunes a asignar.
     */
    public void setComunes(Comunes comunes) {
        dEv = comunes.getDAOEV();
        dArt = comunes.getDAOART();
        dTec = comunes.getDAOTEC();
        modal = comunes.getMODAL();
        parent = comunes.getPARENT();
    }
    
    /**
     * Setea los campos con los que va a operar la botonera.
     * @param campos Mapa con los campos a operar.
     */
    public void setCampos(HashMap<String, Component> campos) {
        this.campos = campos;
    }

    /**
     * Setea el tipo de entidad con la que se va a trabajar.
     * @param tipo Tipo de la entidad.
     */
    public void setTipo(int tipo) {
        this.tipo = tipo;
    }

    /**
     * Asigna una tabla a la botonera.
     * @param tabla Tabla a asignar.
     */
    public void setTabla(TblRider tabla) {
        this.tabla = tabla;
    }

    /**
     * Setea un Frame (la ventana de la interfaz) para mostrar ventanas modales.
     * @param parent Framee (Interfaz) a asignar.
     */
    public void setParent(Interfaz parent) {
        this.parent = parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLimpiar = new components.atoms.ImgButton();
        btnGuardar = new components.atoms.ImgButton();

        setBackground(Colores.TRANSPARENTE);

        btnLimpiar.setIcon(Botones.LIMPIAR);
        btnLimpiar.setTipo(Botones.BTN_LIMPIAR);
        btnLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarMouseClicked(evt);
            }
        });

        btnGuardar.setIcon(Botones.GUARDAR);
        btnGuardar.setTipo(Botones.BTN_GUARDAR);
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Limpia los campos de la vista.
     * @param evt Evento de ratón.
     */
    private void btnLimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarMouseClicked
        Operaciones.limpiar(campos);
    }//GEN-LAST:event_btnLimpiarMouseClicked

    /**
     * Guarda un nuevo registro.
     * @param evt Evento de ratón.
     */
    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        ArrayList<Component> lista = new ArrayList();
        boolean guardado = false;
        switch (tipo) {
            case Comunes.TIPO_EVENTO:
                lista = parent.getCamposActualizarEventos();
                guardado = guardaEvento();                
                break;
            case Comunes.TIPO_ARTISTA:   
                lista = parent.getCamposActualizarArtistas();
                guardado = guardaArtista();
                break;
            case Comunes.TIPO_TECNICO:
                lista = parent.getCamposActualizarTecnicos();
                guardado = guardaTecnico();
                break;
        }
        if (guardado) {
            Operaciones.actualizaDatos(lista);
            Operaciones.limpiar(campos);
        }
        
    }//GEN-LAST:event_btnGuardarMouseClicked
    
    /**
     * Almacena un nuevo técnico.
     * @return True si se ha podido registrar. False en caso contrario.
     */
    private boolean guardaTecnico() {
        Tecnico t = Operaciones.compruebaCamposTecnico(campos, modal);
        
        if (t != null) {
            if (dTec.insertar(t)) {
                modal.setTipo(Modal.MODAL_OK);
                modal.setText("Técnico guardado con éxito.");
            } else {
                modal.setTipo(Modal.MODAL_ERROR);
                modal.setText("No se pudo guardar el técnico.");
            }
        }
        
        modal.setOpciones(false);
        modal.showDialog();
        
        return t != null;
    }
    
    /**
     * Almacena un nuevo artista.
     * @return True si se ha podido registrar. False en caso contrario.
     */
    private boolean guardaArtista() {
        Artista a = Operaciones.compruebaCamposArtista(campos, modal);        
        
        if (a != null) {
            if (dArt.insertar(a)) {
                modal.setTipo(Modal.MODAL_OK);
                modal.setText("Artista guardado con éxito.");
            } else {
                modal.setTipo(Modal.MODAL_ERROR);
                modal.setText("No se pudo guardar el artista.");
            }                
        }        
        modal.setOpciones(false);
        modal.showDialog();
        
        return a != null;
    }

    /**
     * Almacena un nuevo evento.
     * @return True si se ha podido registrar. False en caso contrario.
     */
    private boolean guardaEvento() {
        Evento e = Operaciones.compruebaCamposEvento(campos, modal);
        
        if (e != null) {
            if (dEv.insertar(e)) {
                modal.setTipo(Modal.MODAL_OK);
                modal.setText("Evento guardado con éxito.");
            }
            else {                
                modal.setTipo(Modal.MODAL_ERROR);
                modal.setText("No se pudo guardar el evento.");
            }
        } else {
            modal.setTipo(Modal.MODAL_WARNING);
        }
        
        if(!modal.getText().contains("No has añadido")) {
            modal.setOpciones(false);
            modal.showDialog();
        }
        
        return e != null;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private components.atoms.ImgButton btnGuardar;
    private components.atoms.ImgButton btnLimpiar;
    // End of variables declaration//GEN-END:variables

}
