package vistas;

import assets.objects.Comunes;
import assets.objects.Listeners;
import assets.lookandfeel.Botones;
import assets.lookandfeel.Colores;
import GUI.Container;
import POJOs.Artista;
import assets.lookandfeel.Bordes;
import assets.lookandfeel.Fuentes;
import assets.lookandfeel.Iconos;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import java.util.HashMap;

/**
 *
 * @author José Francisco Blasco Jiménez
 */
public class ArtistasResultado extends javax.swing.JPanel {
    private HashMap<String, Component> campos;
    private ArrayList<Component> ocultar;
    private Container container;

    /**
     * Creates new form NuevoEvento
     */
    public ArtistasResultado() {
        initComponents();
        setCampos();
    }
    
    public void setComunes(Comunes comunes) {
        seteaMovidasDeComponentes(comunes);
    }
    
    private void seteaMovidasDeComponentes(Comunes comunes) {
        txtMail.setComunes(comunes);
        txtNombre.setComunes(comunes);
        txtTlf.setComunes(comunes);
        botonera.setComunes(comunes);
        pnlRiderAdd.setComunes(comunes);
        pnlRiderAdd.setVisible(false);
        tblRider.setTipo(Comunes.TIPO_ARTISTA);
        txtNombre.setRequerido(true);
        txtNombre.getTextField().getDocument().addDocumentListener(comunes.getListeners().getREQUERIDO());
        txtTlf.getTextField().addKeyListener(comunes.getListeners().getNUMEROS());
        txtMail.getTextField().getDocument().addDocumentListener(comunes.getListeners().getMAIL());
        ocultar = new ArrayList();
        ocultar.add(pnlRiderAdd);
        botonera.setCamposOcultar(ocultar);
        botonera.setParent(comunes.getPARENT());
        pnlRiderAdd.setTblRider(tblRider);
    }

    public void setArtista(Artista art) {
        botonera.setActual(art);
    }

    public void setCampos() {
        campos = new HashMap();
        campos.put("txtNombre", txtNombre);
        campos.put("txtTlf", txtTlf);
        campos.put("txtMail", txtMail);
        campos.put("txtObservaciones", txtObservaciones);
        campos.put("tblRider", tblRider);
        pnlRiderAdd.addCampos(campos);
        botonera.setCampos(campos);
    }

    public void setContainer(Container c) {
        setComunes(c.getComunes());
        botonera.setContainer(c);
    }
    
    public void setCard(CardLayout card) {
        botonera.setCard(card);
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlNuevoArtista = new components.atoms.RoundPanel();
        lblMail = new components.atoms.Label();
        txtNombre = new components.atoms.txt.RoundTextField();
        separador = new javax.swing.JSeparator();
        txtTlf = new components.atoms.txt.RoundTextField();
        txtMail = new components.atoms.txt.RoundTextField();
        lblNombre = new components.atoms.Label();
        lblTlf = new components.atoms.Label();
        tblRider = new components.organisms.tables.TblRider();
        lblRider = new components.atoms.Label();
        txtObservaciones = new components.atoms.txt.RoundTextArea();
        lblObservaciones = new components.atoms.Label();
        botonera = new components.organisms.keypads.KeyResultado();
        pnlRiderAdd = new components.molecules.PnlRiderAdd();

        setBackground(Colores.TRANSPARENTE);
        setPreferredSize(new java.awt.Dimension(800, 600));

        pnlNuevoArtista.setBackground(Colores.GRISAZUL);
        pnlNuevoArtista.setPreferredSize(new java.awt.Dimension(800, 600));
        pnlNuevoArtista.setRoundBottomRight(99);
        pnlNuevoArtista.setRoundTopRight(99);

        lblMail.setText("E-mail");

        txtNombre.setLabel(lblNombre);

        separador.setBackground(Colores.BLANCO);
        separador.setForeground(Colores.BLANCO);

        txtTlf.setLabel(lblTlf);

        txtMail.setLabel(lblMail);

        lblNombre.setText("Nombre");

        lblTlf.setText("Teléfono");

        tblRider.setLabel(lblRider);

        lblRider.setText("Rider");
        lblRider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRiderMouseClicked(evt);
            }
        });

        lblObservaciones.setText("Observaciones");

        javax.swing.GroupLayout pnlNuevoArtistaLayout = new javax.swing.GroupLayout(pnlNuevoArtista);
        pnlNuevoArtista.setLayout(pnlNuevoArtistaLayout);
        pnlNuevoArtistaLayout.setHorizontalGroup(
            pnlNuevoArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNuevoArtistaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botonera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addGroup(pnlNuevoArtistaLayout.createSequentialGroup()
                .addGroup(pnlNuevoArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlNuevoArtistaLayout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(tblRider, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlNuevoArtistaLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(pnlNuevoArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlNuevoArtistaLayout.createSequentialGroup()
                                .addGroup(pnlNuevoArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnlNuevoArtistaLayout.createSequentialGroup()
                                        .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlNuevoArtistaLayout.createSequentialGroup()
                                        .addComponent(lblTlf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtTlf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlNuevoArtistaLayout.createSequentialGroup()
                                        .addComponent(lblMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(13, 13, 13)
                                        .addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(lblObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlNuevoArtistaLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(pnlNuevoArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(pnlRiderAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlNuevoArtistaLayout.createSequentialGroup()
                                        .addComponent(lblRider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        pnlNuevoArtistaLayout.setVerticalGroup(
            pnlNuevoArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNuevoArtistaLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(pnlNuevoArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlNuevoArtistaLayout.createSequentialGroup()
                        .addGroup(pnlNuevoArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlNuevoArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTlf, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTlf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlNuevoArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblMail, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(pnlNuevoArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(pnlRiderAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(tblRider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(botonera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlNuevoArtista, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlNuevoArtista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblRiderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRiderMouseClicked
        System.out.println("ARTISTAS NUEVO:\t" + getWidth());
    }//GEN-LAST:event_lblRiderMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private components.organisms.keypads.KeyResultado botonera;
    private components.atoms.Label lblMail;
    private components.atoms.Label lblNombre;
    private components.atoms.Label lblObservaciones;
    private components.atoms.Label lblRider;
    private components.atoms.Label lblTlf;
    private components.atoms.RoundPanel pnlNuevoArtista;
    private components.molecules.PnlRiderAdd pnlRiderAdd;
    private javax.swing.JSeparator separador;
    private components.organisms.tables.TblRider tblRider;
    private components.atoms.txt.RoundTextField txtMail;
    private components.atoms.txt.RoundTextField txtNombre;
    private components.atoms.txt.RoundTextArea txtObservaciones;
    private components.atoms.txt.RoundTextField txtTlf;
    // End of variables declaration//GEN-END:variables

}
