package vistas;

import assets.objects.Comunes;
import assets.objects.Listeners;
import assets.lookandfeel.Botones;
import assets.lookandfeel.Colores;
import java.awt.Component;
import GUI.Container;
import assets.lookandfeel.Bordes;
import assets.lookandfeel.Fuentes;
import assets.lookandfeel.Iconos;
import java.util.HashMap;

/**
 *
 * @author José Francisco Blasco Jiménez
 */
public class ArtistasNuevo extends javax.swing.JPanel {
    private HashMap<String, Component> campos;
    private Container container;

    /**
     * Creates new form NuevoEvento
     */
    public ArtistasNuevo() {
        initComponents();
        setCampos();
    }

    public void setComunes(Comunes comunes) {
        seteaMovidasDeComponentes(comunes);
    }
    
    private void seteaMovidasDeComponentes(Comunes comunes) {
        txtMail.setComunes(comunes);
        txtNombre.setComunes(comunes);
        txtTlf.setComunes(comunes);
        tblRider.setComunes(comunes);
        botonera.setComunes(comunes);
        pnlRiderAdd.setComunes(comunes);
        botonera.setParent(comunes.getPARENT());
        botonera.setTipo(Comunes.TIPO_ARTISTA);
        tblRider.setTipo(Comunes.TIPO_ARTISTA);
        botonera.setTabla(tblRider);
        txtNombre.getTextField().getDocument().addDocumentListener(comunes.getListeners().getREQUERIDO());
        txtTlf.getTextField().addKeyListener(comunes.getListeners().getNUMEROS());
        txtMail.getTextField().getDocument().addDocumentListener(comunes.getListeners().getMAIL());
        pnlRiderAdd.setTblRider(tblRider);
    }

    private void setCampos() {
        campos = new HashMap();
        campos.put("txtNombre", txtNombre);
        campos.put("txtTlf", txtTlf);
        campos.put("txtMail", txtMail);
        campos.put("txtObservaciones", txtObservaciones);
        campos.put("tblRider", tblRider);
        botonera.setCampos(campos);
    }
    
    

    public void setContainer(Container c) {
        setComunes(c.getComunes());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlNuevoEvento = new components.atoms.RoundPanel();
        lblNombre = new components.atoms.Label();
        lblTlf = new components.atoms.Label();
        tblRider = new components.organisms.tables.TblRider();
        lblRider = new components.atoms.Label();
        txtObservaciones = new components.atoms.txt.RoundTextArea();
        lblObservaciones = new components.atoms.Label();
        lblMail = new components.atoms.Label();
        separador = new javax.swing.JSeparator();
        botonera = new components.organisms.keypads.KeyNuevo();
        txtNombre = new components.atoms.txt.RoundTextField();
        txtTlf = new components.atoms.txt.RoundTextField();
        txtMail = new components.atoms.txt.RoundTextField();
        pnlRiderAdd = new components.molecules.PnlRiderAdd();

        setBackground(Colores.TRANSPARENTE);
        setPreferredSize(new java.awt.Dimension(800, 600));

        pnlNuevoEvento.setBackground(Colores.GRISAZUL);
        pnlNuevoEvento.setPreferredSize(new java.awt.Dimension(800, 600));
        pnlNuevoEvento.setRoundBottomRight(99);
        pnlNuevoEvento.setRoundTopRight(99);

        lblNombre.setText("Nombre");

        lblTlf.setText("Teléfono");

        tblRider.setLabel(lblRider);

        lblRider.setText("Rider");

        lblObservaciones.setText("Observaciones");

        lblMail.setText("E-mail");

        separador.setBackground(Colores.BLANCO);
        separador.setForeground(Colores.BLANCO);

        txtNombre.setLabel(lblNombre);
        txtNombre.setRequerido(true);

        txtTlf.setLabel(lblTlf);

        txtMail.setLabel(lblMail);

        javax.swing.GroupLayout pnlNuevoEventoLayout = new javax.swing.GroupLayout(pnlNuevoEvento);
        pnlNuevoEvento.setLayout(pnlNuevoEventoLayout);
        pnlNuevoEventoLayout.setHorizontalGroup(
            pnlNuevoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNuevoEventoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botonera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addGroup(pnlNuevoEventoLayout.createSequentialGroup()
                .addGroup(pnlNuevoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlNuevoEventoLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(pnlNuevoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlNuevoEventoLayout.createSequentialGroup()
                                .addGroup(pnlNuevoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnlNuevoEventoLayout.createSequentialGroup()
                                        .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlNuevoEventoLayout.createSequentialGroup()
                                        .addComponent(lblTlf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtTlf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlNuevoEventoLayout.createSequentialGroup()
                                        .addComponent(lblMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(13, 13, 13)
                                        .addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(lblObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlNuevoEventoLayout.createSequentialGroup()
                                .addComponent(lblRider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlNuevoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pnlRiderAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(pnlNuevoEventoLayout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(tblRider, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        pnlNuevoEventoLayout.setVerticalGroup(
            pnlNuevoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNuevoEventoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnlNuevoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlNuevoEventoLayout.createSequentialGroup()
                        .addGroup(pnlNuevoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblObservaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlNuevoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTlf, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTlf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlNuevoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblMail, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(pnlNuevoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlRiderAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tblRider, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlNuevoEvento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlNuevoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private components.organisms.keypads.KeyNuevo botonera;
    private components.atoms.Label lblMail;
    private components.atoms.Label lblNombre;
    private components.atoms.Label lblObservaciones;
    private components.atoms.Label lblRider;
    private components.atoms.Label lblTlf;
    private components.atoms.RoundPanel pnlNuevoEvento;
    private components.molecules.PnlRiderAdd pnlRiderAdd;
    private javax.swing.JSeparator separador;
    private components.organisms.tables.TblRider tblRider;
    private components.atoms.txt.RoundTextField txtMail;
    private components.atoms.txt.RoundTextField txtNombre;
    private components.atoms.txt.RoundTextArea txtObservaciones;
    private components.atoms.txt.RoundTextField txtTlf;
    // End of variables declaration//GEN-END:variables

}
