package vistas;

import assets.lookandfeel.Botones;
import assets.lookandfeel.Colores;
import assets.lookandfeel.Bordes;
import GUI.Container;
import assets.lookandfeel.Fuentes;
import assets.objects.Comunes;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.*;

/**
 *
 * @author José Francisco Blasco Jiménez
 */
public class EventosListado extends javax.swing.JPanel {
    private HashMap<String, Component> campos;
    
    /**
     * Creates new form NuevoEvento
     */
    public EventosListado() {        
        initComponents();
        setCampos();
    }
    
    public void setComunes(Comunes comunes) {
        seteaMovidasDeComponentes(comunes);
    }
    
    private void seteaMovidasDeComponentes(Comunes comunes) {
        txtAl.setComunes(comunes);
        txtDel.setComunes(comunes);
        txtId.setComunes(comunes);
        txtNombre.setComunes(comunes);
        tblEventos.setComunes(comunes);
        botonera.setComunes(comunes);
        botoneraFiltro.setComunes(comunes);
        tblEventos.setComunes(comunes);
        dateChooserDel.setTextRefernce(txtDel.getTextField());
        dateChooserAl.setTextRefernce(txtAl.getTextField());
        tblEventos.setTipo(0);
        botoneraFiltro.setTabla(tblEventos);
        botonera.setTabla(tblEventos);
        cmbTecnico.setComunes(comunes);
        cmbTecnico.setTipo(Comunes.TIPO_TECNICO);
        cmbTecnico.setListarCero(true);
        cmbArtista.setComunes(comunes);
        cmbArtista.setTipo(Comunes.TIPO_ARTISTA);
        cmbArtista.setListarCero(true);
        botonera.setParent(comunes.getPARENT());
        botoneraFiltro.setParent(comunes.getPARENT());
    }

    private void setCampos() {
        campos = new HashMap();
        campos.put("txtId", txtId);
        campos.put("txtNombre", txtNombre);
        campos.put("txtFechaDel", txtDel);
        campos.put("txtFechaAl", txtAl);
        campos.put("cmbTecnico", cmbTecnico);
        campos.put("artistas", cmbTecnico);
        botoneraFiltro.setCampos(campos);
    }
    
    public void setContainer(Container c) {
        setComunes(c.getComunes());
        tblEventos.setContainer(c);
        c.getFrame().getCamposActualizarEventos().add(tblEventos);
        c.getFrame().getCamposActualizarArtistas().add(tblEventos);
        c.getFrame().getCamposActualizarArtistas().add(cmbArtista);
        c.getFrame().getCamposActualizarTecnicos().add(tblEventos);
        c.getFrame().getCamposActualizarTecnicos().add(cmbTecnico);
    }
    
    public void setCard(CardLayout card) {
        tblEventos.setCard(card);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooserDel = new components.datechooser.DateChooser();
        dateChooserAl = new components.datechooser.DateChooser();
        pnlEventosListado = new components.atoms.RoundPanel();
        pnlFiltro = new components.atoms.RoundPanel();
        lblNombre = new components.atoms.Label();
        lblTecnico = new components.atoms.Label();
        pnlFecha = new components.atoms.RoundPanel();
        lblDel = new components.atoms.Label();
        bntDel = new components.atoms.ImgButton();
        lblAl = new components.atoms.Label();
        btnAl = new components.atoms.ImgButton();
        txtDel = new components.atoms.txt.RoundTextField();
        txtAl = new components.atoms.txt.RoundTextField();
        lblFecha = new components.atoms.Label();
        jSeparator1 = new javax.swing.JSeparator();
        cmbTecnico = new components.atoms.combo.CustomComboBox();
        botoneraFiltro = new components.organisms.keypads.KeyFiltro();
        lblArtista = new components.atoms.Label();
        cmbArtista = new components.atoms.combo.CustomComboBox();
        txtNombre = new components.atoms.txt.RoundTextField();
        txtId = new components.atoms.txt.RoundTextField();
        lblFiltros = new components.atoms.Label();
        tblEventos = new components.organisms.tables.TblListado();
        botonera = new components.organisms.keypads.KeyListado();

        dateChooserDel.setForeground(Colores.NARANJA);

        dateChooserAl.setForeground(Colores.NARANJA);

        setBackground(Colores.TRANSPARENTE);

        pnlEventosListado.setBackground(Colores.GRISAZUL);
        pnlEventosListado.setPreferredSize(new java.awt.Dimension(800, 600));
        pnlEventosListado.setRoundBottomRight(99);
        pnlEventosListado.setRoundTopRight(99);

        pnlFiltro.setBackground(Colores.TRANSPARENTE);
        pnlFiltro.setBorder(Bordes.GRIS40);
        pnlFiltro.setPreferredSize(new java.awt.Dimension(696, 164));
        pnlFiltro.setRoundBottomLeft(40);
        pnlFiltro.setRoundBottomRight(40);
        pnlFiltro.setRoundTopLeft(40);
        pnlFiltro.setRoundTopRight(40);

        lblNombre.setText("Nombre");

        lblTecnico.setText("Técnico");

        pnlFecha.setBackground(Colores.TRANSPARENTE);
        pnlFecha.setBorder(Bordes.GRIS40);
        pnlFecha.setRoundBottomLeft(40);
        pnlFecha.setRoundBottomRight(40);
        pnlFecha.setRoundTopLeft(40);
        pnlFecha.setRoundTopRight(40);

        lblDel.setText("Del");

        bntDel.setIcon(new javax.swing.ImageIcon("assets\\buttons\\CalendarNormal.png"));
        bntDel.setTipo(Botones.BTN_CALENDAR);
        bntDel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntDelMouseClicked(evt);
            }
        });

        lblAl.setText("Al");

        btnAl.setTipo(Botones.BTN_CALENDAR);
        btnAl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAlMouseClicked(evt);
            }
        });

        txtDel.setLabel(lblDel);

        txtAl.setLabel(lblAl);

        javax.swing.GroupLayout pnlFechaLayout = new javax.swing.GroupLayout(pnlFecha);
        pnlFecha.setLayout(pnlFechaLayout);
        pnlFechaLayout.setHorizontalGroup(
            pnlFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFechaLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblDel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDel, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(bntDel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblAl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAl, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(btnAl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        pnlFechaLayout.setVerticalGroup(
            pnlFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFechaLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(pnlFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlFechaLayout.createSequentialGroup()
                        .addGroup(pnlFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlFechaLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(pnlFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtAl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblAl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(bntDel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblDel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtDel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        lblFecha.setText("Fecha");

        jSeparator1.setBackground(Colores.BLANCO);
        jSeparator1.setForeground(Colores.BLANCO);
        jSeparator1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N

        cmbTecnico.setFont(Fuentes.REGULAR);
        cmbTecnico.setTipo(3);

        lblArtista.setText("Artista");

        cmbArtista.setFont(Fuentes.REGULAR);
        cmbArtista.setTipo(3);

        txtNombre.setLabel(lblNombre);

        txtId.setLabel(lblNombre);

        javax.swing.GroupLayout pnlFiltroLayout = new javax.swing.GroupLayout(pnlFiltro);
        pnlFiltro.setLayout(pnlFiltroLayout);
        pnlFiltroLayout.setHorizontalGroup(
            pnlFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFiltroLayout.createSequentialGroup()
                .addGroup(pnlFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlFiltroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botoneraFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlFiltroLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(pnlFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlFiltroLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlFiltroLayout.createSequentialGroup()
                                .addGroup(pnlFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(pnlFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pnlFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlFiltroLayout.createSequentialGroup()
                                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(cmbTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblArtista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(cmbArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        pnlFiltroLayout.setVerticalGroup(
            pnlFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFiltroLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(pnlFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlFiltroLayout.createSequentialGroup()
                        .addGroup(pnlFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTecnico, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cmbTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cmbArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(2, 2, 2)))
                .addGap(6, 6, 6)
                .addGroup(pnlFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFiltroLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(botoneraFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9))
        );

        lblFiltros.setText("Filtros");

        javax.swing.GroupLayout pnlEventosListadoLayout = new javax.swing.GroupLayout(pnlEventosListado);
        pnlEventosListado.setLayout(pnlEventosListadoLayout);
        pnlEventosListadoLayout.setHorizontalGroup(
            pnlEventosListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEventosListadoLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(pnlEventosListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tblEventos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEventosListadoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        pnlEventosListadoLayout.setVerticalGroup(
            pnlEventosListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEventosListadoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(pnlFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tblEventos, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(botonera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlEventosListado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlEventosListado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bntDelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntDelMouseClicked
        dateChooserDel.showPopup();
    }//GEN-LAST:event_bntDelMouseClicked

    private void btnAlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlMouseClicked
        dateChooserAl.showPopup();
    }//GEN-LAST:event_btnAlMouseClicked
    
    private void limpiar() {
        txtNombre.setText(null);
        txtAl.setText(null);
        txtDel.setText(null);
        txtId.setText(null);
        cmbArtista.setSelectedItem(-1);
        cmbTecnico.setSelectedItem(-1);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private components.atoms.ImgButton bntDel;
    private components.organisms.keypads.KeyListado botonera;
    private components.organisms.keypads.KeyFiltro botoneraFiltro;
    private components.atoms.ImgButton btnAl;
    private components.atoms.combo.CustomComboBox cmbArtista;
    private components.atoms.combo.CustomComboBox cmbTecnico;
    private components.datechooser.DateChooser dateChooserAl;
    private components.datechooser.DateChooser dateChooserDel;
    private javax.swing.JSeparator jSeparator1;
    private components.atoms.Label lblAl;
    private components.atoms.Label lblArtista;
    private components.atoms.Label lblDel;
    private components.atoms.Label lblFecha;
    private components.atoms.Label lblFiltros;
    private components.atoms.Label lblNombre;
    private components.atoms.Label lblTecnico;
    private components.atoms.RoundPanel pnlEventosListado;
    private components.atoms.RoundPanel pnlFecha;
    private components.atoms.RoundPanel pnlFiltro;
    private components.organisms.tables.TblListado tblEventos;
    private components.atoms.txt.RoundTextField txtAl;
    private components.atoms.txt.RoundTextField txtDel;
    private components.atoms.txt.RoundTextField txtId;
    private components.atoms.txt.RoundTextField txtNombre;
    // End of variables declaration//GEN-END:variables

}
