package vistas;

import assets.objects.Comunes;
import assets.lookandfeel.Botones;
import assets.lookandfeel.Colores;
import GUI.Container;
import POJOs.*;
import assets.lookandfeel.Bordes;
import assets.lookandfeel.Fuentes;
import assets.objects.Listeners;
import components.atoms.txt.RoundTextField;
import java.awt.CardLayout;
import java.awt.Component;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.HashMap;

/**
 *
 * @author José Francisco Blasco Jiménez
 */
public class EventosResultado extends javax.swing.JPanel {    
    private HashMap<String, Component> campos;
    private ArrayList<Component> ocultar;
    /**
     * Creates new form NuevoEvento
     */
    public EventosResultado() {
        initComponents();
        setCampos();
        
    }
    
    public void setcomunes(Comunes comunes) {
        seteaMovidasDeComponentes(comunes);
    }
    
    private void seteaMovidasDeComponentes(Comunes comunes) {
        txtFecha.setComunes(comunes);
        txtNombre.setComunes(comunes);
        tblRider.setComunes(comunes);
        cmbTecnico.setComunes(comunes);
        cmbTecnico.setTipo(Comunes.TIPO_TECNICO);
        cmbTecnico.setListarCero(true);
        artistChooser.setComunes(comunes);
        botonera.setComunes(comunes);
        txtNombre.setRequerido(true);
        txtFecha.setRequerido(true);
        txtNombre.getTextField().getDocument().addDocumentListener(comunes.getListeners().getREQUERIDO());
        txtFecha.getTextField().getDocument().addDocumentListener(comunes.getListeners().getFECHA());
        cmbTecnico.setListarCero(false);
        dateChooser.setTextRefernce(txtFecha.getTextField());
        tblRider.setTipo(Comunes.TIPO_EVENTO);
        artistChooser.setRider(tblRider);
        ocultar = new ArrayList();
        ocultar.add(btnFecha);
        botonera.setCamposOcultar(ocultar);
        botonera.setParent(comunes.getPARENT());
    }

    public void setEv(Evento ev) {
        txtFecha.setEvento(ev);
        botonera.setActual(ev);
        botonera.setModificarOption(ev.getFecha().isAfter(LocalDate.now()));
        
    }
    
    public void setContainer(Container c) {
        setcomunes(c.getComunes());
        botonera.setContainer(c);
        c.getFrame().getCamposActualizarArtistas().add(artistChooser);
        c.getFrame().getCamposActualizarTecnicos().add(cmbTecnico);
    }
    
    public void setCard(CardLayout card) {
        botonera.setCard(card);
    }
    
    public void setCampos() {
        this.campos = new HashMap();
        campos.put("txtNombre", txtNombre);
        campos.put("txtFecha", txtFecha);
        campos.put("cmbTecnico", cmbTecnico);
        campos.put("chooser", artistChooser);
        campos.put("artistas", artistChooser);
        campos.put("tblRider", tblRider);
        campos.put("txtObsArtistas", txtObsArtistas);
        campos.put("txtObsEvento", txtObsEvento);
        botonera.setCampos(campos);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooser = new components.datechooser.DateChooser();
        pnlNuevoEvento = new components.atoms.RoundPanel();
        lblRider = new components.atoms.Label();
        tblRider = new components.organisms.tables.TblRider();
        txtObsArtistas = new components.atoms.txt.RoundTextArea();
        lblObsArtistas = new components.atoms.Label();
        lblObsEventos = new components.atoms.Label();
        txtNombre = new components.atoms.txt.RoundTextField();
        txtObsEvento = new components.atoms.txt.RoundTextArea();
        btnFecha = new components.atoms.ImgButton();
        lblNombre = new components.atoms.Label();
        artistChooser = new components.artistchooser.ArtistChooser();
        txtFecha = new components.atoms.txt.RoundTextField();
        lblFecha = new components.atoms.Label();
        lblTecnico = new components.atoms.Label();
        cmbTecnico = new components.atoms.combo.CustomComboBox();
        lblArtistas = new components.atoms.Label();
        botonera = new components.organisms.keypads.KeyResultado();

        dateChooser.setForeground(Colores.NARANJA);

        setBackground(Colores.TRANSPARENTE);
        setPreferredSize(new java.awt.Dimension(800, 600));

        pnlNuevoEvento.setBackground(Colores.GRISAZUL);
        pnlNuevoEvento.setPreferredSize(new java.awt.Dimension(812, 600));
        pnlNuevoEvento.setRoundBottomRight(99);
        pnlNuevoEvento.setRoundTopRight(99);

        lblRider.setText("Rider");

        lblObsArtistas.setText("Observaciones artistas");

        lblObsEventos.setText("Observaciones evento");
        lblObsEventos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblObsEventosMouseClicked(evt);
            }
        });

        txtNombre.setLabel(lblNombre);

        btnFecha.setTipo(Botones.BTN_CALENDAR);
        btnFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFechaMouseClicked(evt);
            }
        });

        lblNombre.setText("Nombre");

        txtFecha.setLabel(lblFecha);
        txtFecha.setResultado(true);
        txtFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFechaMouseClicked(evt);
            }
        });

        lblFecha.setText("Fecha");

        lblTecnico.setText("Técnico");

        lblArtistas.setText("Artistas");

        javax.swing.GroupLayout pnlNuevoEventoLayout = new javax.swing.GroupLayout(pnlNuevoEvento);
        pnlNuevoEvento.setLayout(pnlNuevoEventoLayout);
        pnlNuevoEventoLayout.setHorizontalGroup(
            pnlNuevoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNuevoEventoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pnlNuevoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlNuevoEventoLayout.createSequentialGroup()
                        .addGroup(pnlNuevoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(artistChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tblRider, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblArtistas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(pnlNuevoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtObsEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblObsArtistas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtObsArtistas, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblObsEventos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlNuevoEventoLayout.createSequentialGroup()
                        .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNuevoEventoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        pnlNuevoEventoLayout.setVerticalGroup(
            pnlNuevoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNuevoEventoLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(pnlNuevoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlNuevoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtFecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblFecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTecnico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlNuevoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblObsArtistas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblArtistas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(pnlNuevoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlNuevoEventoLayout.createSequentialGroup()
                        .addComponent(artistChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(pnlNuevoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblObsEventos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtObsArtistas, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(pnlNuevoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtObsEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tblRider, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(botonera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlNuevoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlNuevoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnFechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFechaMouseClicked
        dateChooser.showPopup();
    }//GEN-LAST:event_btnFechaMouseClicked

    private void txtFechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFechaMouseClicked
        dateChooser.showPopup();
    }//GEN-LAST:event_txtFechaMouseClicked

    private void lblObsEventosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblObsEventosMouseClicked
        System.out.println("EVENTOS NUEVO:\t" + getWidth());
    }//GEN-LAST:event_lblObsEventosMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private components.artistchooser.ArtistChooser artistChooser;
    private components.organisms.keypads.KeyResultado botonera;
    private components.atoms.ImgButton btnFecha;
    private components.atoms.combo.CustomComboBox cmbTecnico;
    private components.datechooser.DateChooser dateChooser;
    private components.atoms.Label lblArtistas;
    private components.atoms.Label lblFecha;
    private components.atoms.Label lblNombre;
    private components.atoms.Label lblObsArtistas;
    private components.atoms.Label lblObsEventos;
    private components.atoms.Label lblRider;
    private components.atoms.Label lblTecnico;
    private components.atoms.RoundPanel pnlNuevoEvento;
    private components.organisms.tables.TblRider tblRider;
    private components.atoms.txt.RoundTextField txtFecha;
    private components.atoms.txt.RoundTextField txtNombre;
    private components.atoms.txt.RoundTextArea txtObsArtistas;
    private components.atoms.txt.RoundTextArea txtObsEvento;
    // End of variables declaration//GEN-END:variables
}
