package vistas;

import GUI.Container;
import assets.lookandfeel.Bordes;
import assets.objects.Comunes;
import assets.objects.Listeners;
import assets.lookandfeel.Botones;
import assets.lookandfeel.Colores;
import assets.lookandfeel.Fuentes;
import java.awt.Component;
import java.util.HashMap;

/**
 *
 * @author José Francisco Blasco Jiménez
 */
public class EventosNuevo extends javax.swing.JPanel {
    private HashMap<String, Component> campos;
    private Container container;
    
    
    /**
     * Creates new form NuevoEvento
     */
    public EventosNuevo() {
        initComponents();        
        setCampos();
    }
    
    public void setComunes(Comunes comunes) {
        seteaMovidasDeComponentes(comunes);
    }
    
    private void seteaMovidasDeComponentes(Comunes comunes) {
        txtFecha.setComunes(comunes);
        txtNombre.setComunes(comunes);
        tblRider.setComunes(comunes);
        cmbTecnico.setComunes(comunes);
        artistChooser.setComunes(comunes);
        botonera.setComunes(comunes);
        txtNombre.setRequerido(true);
        txtFecha.setRequerido(true);
        txtNombre.getTextField().getDocument().addDocumentListener(comunes.getListeners().getREQUERIDO());
        txtFecha.getTextField().getDocument().addDocumentListener(comunes.getListeners().getFECHA());
        tblRider.setTipo(Comunes.TIPO_EVENTO);
        dateChooser.setTextRefernce(txtFecha.getTextField());
        artistChooser.setRider(tblRider);        
        botonera.setTipo(Comunes.TIPO_EVENTO);
        botonera.setTabla(tblRider);
        txtObsArtistas.getArea().setEditable(false);
        artistChooser.setArea(txtObsArtistas);
        botonera.setParent(comunes.getPARENT());
        cmbTecnico.setTipo(Comunes.TIPO_TECNICO);
        cmbTecnico.setListarCero(false);
    }

    private void setCampos() {
        campos = new HashMap();
        campos.put("txtNombre", txtNombre);
        campos.put("txtFecha", txtFecha);
        campos.put("cmbTecnico", cmbTecnico);
        campos.put("chooser", artistChooser);
        campos.put("txtObsArtistas", txtObsArtistas);
        campos.put("txtObsEvento", txtObsEvento);
        botonera.setCampos(campos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooser = new components.datechooser.DateChooser();
        pnlNuevoEvento = new components.atoms.RoundPanel();
        txtNombre = new components.atoms.txt.RoundTextField();
        lblNombre = new components.atoms.Label();
        txtFecha = new components.atoms.txt.RoundTextField();
        lblFecha = new components.atoms.Label();
        lblTecnico = new components.atoms.Label();
        cmbTecnico = new components.atoms.combo.CustomComboBox();
        lblRider = new components.atoms.Label();
        tblRider = new components.organisms.tables.TblRider();
        txtObsArtistas = new components.atoms.txt.RoundTextArea();
        lblObsArtistas = new components.atoms.Label();
        lblObsEventos = new components.atoms.Label();
        txtObsEvento = new components.atoms.txt.RoundTextArea();
        botonera = new components.organisms.keypads.KeyNuevo();
        btnFecha = new components.atoms.ImgButton();
        artistChooser = new components.artistchooser.ArtistChooser();
        lblArtistas = new components.atoms.Label();

        dateChooser.setForeground(Colores.NARANJA);

        setBackground(Colores.TRANSPARENTE);
        setPreferredSize(new java.awt.Dimension(812, 600));

        pnlNuevoEvento.setBackground(Colores.GRISAZUL);
        pnlNuevoEvento.setPreferredSize(new java.awt.Dimension(812, 600));
        pnlNuevoEvento.setRoundBottomRight(99);
        pnlNuevoEvento.setRoundTopRight(99);

        txtNombre.setLabel(lblNombre);

        lblNombre.setText("Nombre");

        txtFecha.setLabel(lblFecha);
        txtFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFechaMouseClicked(evt);
            }
        });

        lblFecha.setLabelFor(txtFecha);
        lblFecha.setText("Fecha");

        lblTecnico.setText("Técnico");

        cmbTecnico.setModel(cmbTecnico.getModel());
        cmbTecnico.setTipo(3);

        lblRider.setText("Rider");

        lblObsArtistas.setText("Observaciones artistas");

        lblObsEventos.setText("Observaciones evento");

        btnFecha.setTipo(Botones.BTN_CALENDAR);
        btnFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFechaMouseClicked(evt);
            }
        });

        lblArtistas.setText("Artistas");

        javax.swing.GroupLayout pnlNuevoEventoLayout = new javax.swing.GroupLayout(pnlNuevoEvento);
        pnlNuevoEvento.setLayout(pnlNuevoEventoLayout);
        pnlNuevoEventoLayout.setHorizontalGroup(
            pnlNuevoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNuevoEventoLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(pnlNuevoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlNuevoEventoLayout.createSequentialGroup()
                        .addGroup(pnlNuevoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tblRider, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(artistChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblArtistas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69)
                        .addGroup(pnlNuevoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtObsEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblObsArtistas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtObsArtistas, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblObsEventos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlNuevoEventoLayout.createSequentialGroup()
                        .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNuevoEventoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        pnlNuevoEventoLayout.setVerticalGroup(
            pnlNuevoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNuevoEventoLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(pnlNuevoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlNuevoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtFecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                        .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblFecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTecnico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbTecnico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlNuevoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlNuevoEventoLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblObsArtistas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNuevoEventoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblArtistas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(pnlNuevoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlNuevoEventoLayout.createSequentialGroup()
                        .addComponent(txtObsArtistas, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(pnlNuevoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblObsEventos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlNuevoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlNuevoEventoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtObsEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNuevoEventoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                                .addComponent(tblRider, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(botonera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(pnlNuevoEventoLayout.createSequentialGroup()
                        .addComponent(artistChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlNuevoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlNuevoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtFechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFechaMouseClicked
        dateChooser.showPopup();
    }//GEN-LAST:event_txtFechaMouseClicked

    private void btnFechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFechaMouseClicked
        dateChooser.showPopup();
    }//GEN-LAST:event_btnFechaMouseClicked

    public void setContainer(Container c) {
        container = c;
        setComunes(c.getComunes());
        c.getFrame().getCamposActualizarArtistas().add(artistChooser);
        c.getFrame().getCamposActualizarTecnicos().add(cmbTecnico);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private components.artistchooser.ArtistChooser artistChooser;
    private components.organisms.keypads.KeyNuevo botonera;
    private components.atoms.ImgButton btnFecha;
    private components.atoms.combo.CustomComboBox cmbTecnico;
    private components.datechooser.DateChooser dateChooser;
    private components.atoms.Label lblArtistas;
    private components.atoms.Label lblFecha;
    private components.atoms.Label lblNombre;
    private components.atoms.Label lblObsArtistas;
    private components.atoms.Label lblObsEventos;
    private components.atoms.Label lblRider;
    private components.atoms.Label lblTecnico;
    private components.atoms.RoundPanel pnlNuevoEvento;
    private components.organisms.tables.TblRider tblRider;
    private components.atoms.txt.RoundTextField txtFecha;
    private components.atoms.txt.RoundTextField txtNombre;
    private components.atoms.txt.RoundTextArea txtObsArtistas;
    private components.atoms.txt.RoundTextArea txtObsEvento;
    // End of variables declaration//GEN-END:variables
}
