package vistas;

import assets.lookandfeel.Colores;
import GUI.Container;
import GUI.Menu;
import assets.lookandfeel.Fuentes;
import java.awt.CardLayout;
import java.awt.Cursor;
import javax.swing.JFrame;

/**
 *
 * @author José Francisco Blasco Jiménez
 */
public class Home extends javax.swing.JPanel {
    private CardLayout card;
    private Container container;
    private JFrame parent;
    private Menu menu;
    
    /**
     * Creates new form NuevoEvento
     */
    public Home() {
        initComponents();
        pnlAdd.setCursor(new Cursor(Cursor.HAND_CURSOR));
        pnlList.setCursor(new Cursor(Cursor.HAND_CURSOR));
        pnlInformes.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }

    public void setContainer(Container container) {
        this.container = container;
        this.card = container.getCard();
        menu = this.container.getMenu();
    }

    public void setParent(JFrame parent) {
        this.parent = parent;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlHome = new components.atoms.RoundPanel();
        pnlAdd = new components.atoms.RoundPanel();
        lblAdd = new components.atoms.Label();
        btnAdd = new javax.swing.JLabel();
        pnlList = new components.atoms.RoundPanel();
        lblList = new components.atoms.Label();
        btnList = new javax.swing.JLabel();
        pnlInformes = new components.atoms.RoundPanel();
        lblInformes = new components.atoms.Label();
        btnInformes = new javax.swing.JLabel();

        setBackground(Colores.TRANSPARENTE);

        pnlHome.setBackground(Colores.GRISAZUL);
        pnlHome.setPreferredSize(new java.awt.Dimension(800, 600));
        pnlHome.setRoundBottomRight(99);
        pnlHome.setRoundTopRight(99);

        pnlAdd.setBackground(Colores.TRANSPARENTE);
        pnlAdd.setMinimumSize(new java.awt.Dimension(200, 250));
        pnlAdd.setPreferredSize(new java.awt.Dimension(200, 250));
        pnlAdd.setRoundBottomLeft(60);
        pnlAdd.setRoundBottomRight(60);
        pnlAdd.setRoundTopLeft(60);
        pnlAdd.setRoundTopRight(60);
        pnlAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlAddMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlAddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlAddMouseExited(evt);
            }
        });
        pnlAdd.setLayout(new java.awt.GridBagLayout());

        lblAdd.setText("Añadir Eventos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 40, 26, 0);
        pnlAdd.add(lblAdd, gridBagConstraints);

        btnAdd.setIcon(new javax.swing.ImageIcon("assets\\buttons\\Home_Eventos_Add.png"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 12, 0, 0);
        pnlAdd.add(btnAdd, gridBagConstraints);

        pnlList.setBackground(Colores.TRANSPARENTE);
        pnlList.setMinimumSize(new java.awt.Dimension(200, 200));
        pnlList.setPreferredSize(new java.awt.Dimension(200, 250));
        pnlList.setRoundBottomLeft(60);
        pnlList.setRoundBottomRight(60);
        pnlList.setRoundTopLeft(60);
        pnlList.setRoundTopRight(60);
        pnlList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlListMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlListMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlListMouseExited(evt);
            }
        });
        pnlList.setLayout(new java.awt.GridBagLayout());

        lblList.setText("Listado de Eventos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 30, 26, 0);
        pnlList.add(lblList, gridBagConstraints);

        btnList.setIcon(new javax.swing.ImageIcon("assets\\buttons\\Home_Eventos_List.png"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 6, 0, 0);
        pnlList.add(btnList, gridBagConstraints);

        pnlInformes.setBackground(Colores.TRANSPARENTE);
        pnlInformes.setMinimumSize(new java.awt.Dimension(200, 250));
        pnlInformes.setPreferredSize(new java.awt.Dimension(200, 200));
        pnlInformes.setRoundBottomLeft(60);
        pnlInformes.setRoundBottomRight(60);
        pnlInformes.setRoundTopLeft(60);
        pnlInformes.setRoundTopRight(60);
        pnlInformes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlInformesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlInformesMouseExited(evt);
            }
        });
        pnlInformes.setLayout(new java.awt.GridBagLayout());

        lblInformes.setText("Informes");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 26, 0);
        pnlInformes.add(lblInformes, gridBagConstraints);

        btnInformes.setIcon(new javax.swing.ImageIcon("assets\\buttons\\Home_Informes.png"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(26, 0, 0, 0);
        pnlInformes.add(btnInformes, gridBagConstraints);

        javax.swing.GroupLayout pnlHomeLayout = new javax.swing.GroupLayout(pnlHome);
        pnlHome.setLayout(pnlHomeLayout);
        pnlHomeLayout.setHorizontalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(pnlAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlInformes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );
        pnlHomeLayout.setVerticalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlInformes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(175, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pnlAddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAddMouseEntered
        pnlAdd.setBackground(Colores.BLANCO);
    }//GEN-LAST:event_pnlAddMouseEntered

    private void pnlAddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAddMouseExited
        pnlAdd.setBackground(Colores.TRANSPARENTE);
    }//GEN-LAST:event_pnlAddMouseExited

    private void pnlListMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlListMouseEntered
        pnlList.setBackground(Colores.BLANCO);
        
    }//GEN-LAST:event_pnlListMouseEntered

    private void pnlListMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlListMouseExited
        pnlList.setBackground(Colores.TRANSPARENTE);
    }//GEN-LAST:event_pnlListMouseExited

    private void pnlInformesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlInformesMouseEntered
        pnlInformes.setBackground(Colores.BLANCO);
    }//GEN-LAST:event_pnlInformesMouseEntered

    private void pnlInformesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlInformesMouseExited
        pnlInformes.setBackground(Colores.TRANSPARENTE);
    }//GEN-LAST:event_pnlInformesMouseExited

    private void pnlAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAddMouseClicked
        menu.homeClickHandler("nuevo");
    }//GEN-LAST:event_pnlAddMouseClicked

    private void pnlListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlListMouseClicked
        menu.homeClickHandler("list");
        
    }//GEN-LAST:event_pnlListMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAdd;
    private javax.swing.JLabel btnInformes;
    private javax.swing.JLabel btnList;
    private components.atoms.Label lblAdd;
    private components.atoms.Label lblInformes;
    private components.atoms.Label lblList;
    private components.atoms.RoundPanel pnlAdd;
    private components.atoms.RoundPanel pnlHome;
    private components.atoms.RoundPanel pnlInformes;
    private components.atoms.RoundPanel pnlList;
    // End of variables declaration//GEN-END:variables
}
