package vistas;

import assets.lookandfeel.Colores;
import GUI.Container;
import POJOs.Tecnico;
import assets.objects.Comunes;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.HashMap;

/**
 *
 * @author José Francisco Blasco Jiménez
 */
public class TecnicosResultado extends javax.swing.JPanel {
    private HashMap<String, Component> campos;

    /**
     * Creates new form NuevoEvento
     */
    public TecnicosResultado() {
        initComponents();
        setCampos();
    }

    public void setComunes(Comunes comunes) {
        txtNombre.setComunes(comunes);
        botonera.setComunes(comunes);
        botonera.setParent(comunes.getPARENT());
        seteaListenersYDemas(comunes);
    }
    
    private void seteaListenersYDemas(Comunes comunes) {
        txtNombre.setRequerido(true);
        txtNombre.getTextField().getDocument().addDocumentListener(comunes.getListeners().getREQUERIDO());
        txtTlf.getTextField().addKeyListener(comunes.getListeners().getNUMEROS());
        txtMail.getTextField().getDocument().addDocumentListener(comunes.getListeners().getMAIL());
    }

    public void setTec(Tecnico tec) {
        botonera.setActual(tec);
    }

    public void setCampos() {
        campos = new HashMap();
        campos.put("txtNombre", txtNombre);
        campos.put("txtTlf", txtTlf);
        campos.put("txtMail", txtMail);
        botonera.setCampos(campos);
    }

    public void setContainer(Container c) {
        botonera.setContainer(c);
        botonera.setCard(c.getCard());
        setComunes(c.getComunes());
    }
    
    public void setCard(CardLayout card) {
        botonera.setCard(card);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlNuevoEvento = new components.atoms.RoundPanel();
        txtNombre = new components.atoms.txt.RoundTextField();
        lblNombre = new components.atoms.Label();
        txtTlf = new components.atoms.txt.RoundTextField();
        lblTlf = new components.atoms.Label();
        lblMail = new components.atoms.Label();
        txtMail = new components.atoms.txt.RoundTextField();
        botonera = new components.organisms.keypads.KeyResultado();

        setBackground(Colores.TRANSPARENTE);

        pnlNuevoEvento.setBackground(Colores.GRISAZUL);
        pnlNuevoEvento.setPreferredSize(new java.awt.Dimension(800, 600));
        pnlNuevoEvento.setRoundBottomRight(99);
        pnlNuevoEvento.setRoundTopRight(99);

        txtNombre.setLabel(lblNombre);

        lblNombre.setText("Nombre");

        txtTlf.setLabel(lblTlf);

        lblTlf.setText("Teléfono");

        lblMail.setText("E-mail");

        txtMail.setLabel(lblMail);

        botonera.setTipo(Comunes.TIPO_TECNICO);

        javax.swing.GroupLayout pnlNuevoEventoLayout = new javax.swing.GroupLayout(pnlNuevoEvento);
        pnlNuevoEvento.setLayout(pnlNuevoEventoLayout);
        pnlNuevoEventoLayout.setHorizontalGroup(
            pnlNuevoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNuevoEventoLayout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addGroup(pnlNuevoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlNuevoEventoLayout.createSequentialGroup()
                        .addComponent(lblMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlNuevoEventoLayout.createSequentialGroup()
                        .addGroup(pnlNuevoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTlf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlNuevoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTlf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(260, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNuevoEventoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        pnlNuevoEventoLayout.setVerticalGroup(
            pnlNuevoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNuevoEventoLayout.createSequentialGroup()
                .addContainerGap(213, Short.MAX_VALUE)
                .addGroup(pnlNuevoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlNuevoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTlf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTlf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlNuevoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblMail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtMail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(182, 182, 182)
                .addComponent(botonera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlNuevoEvento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlNuevoEvento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private components.organisms.keypads.KeyResultado botonera;
    private components.atoms.Label lblMail;
    private components.atoms.Label lblNombre;
    private components.atoms.Label lblTlf;
    private components.atoms.RoundPanel pnlNuevoEvento;
    private components.atoms.txt.RoundTextField txtMail;
    private components.atoms.txt.RoundTextField txtNombre;
    private components.atoms.txt.RoundTextField txtTlf;
    // End of variables declaration//GEN-END:variables
}
