/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package components.molecules;

import GUI.Interfaz;
import GUI.Modal;
import assets.lookandfeel.Botones;
import assets.lookandfeel.Colores;
import assets.objects.Comunes;
import components.organisms.tables.TblRider;
import java.awt.Component;
import java.util.HashMap;

/**
 *
 * @author José Francisco Blasco Jiménez
 */
public class PnlRiderAdd extends javax.swing.JPanel {
    private TblRider tblRider;
    private Comunes comunes;
    private Modal modal;
    private Boolean flag;
    private Interfaz parent;
    

    /**
     * Creates new form PnlRiderAdd
     */
    public PnlRiderAdd() {
        initComponents();
    }

    public void addCampos(HashMap<String, Component> campos) {        
        campos.put("txtElemento", txtElemento);
        campos.put("txtCantidad", txtCantidad);
        campos.put("checkSuma", checkSuma);
        campos.put("btnAdd", btnAnadirElemento);
    }

    public TblRider getTblRider() {
        return tblRider;
    }

    public void setTblRider(TblRider tblRider) {
        this.tblRider = tblRider;
    }

    public void setComunes(Comunes comunes) {
        this.comunes = comunes;
        txtCantidad.setComunes(comunes);
        txtElemento.setComunes(comunes);
        modal = comunes.getMODAL();
        txtCantidad.getTextField().addKeyListener(comunes.getListeners().getNUMEROS());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRiderAdd = new javax.swing.JPanel();
        lblSuma = new components.atoms.Label();
        lblElemento = new components.atoms.Label();
        lblCantidad = new components.atoms.Label();
        checkSuma = new components.atoms.RoundCheckBox();
        txtElemento = new components.atoms.txt.RoundTextField();
        txtCantidad = new components.atoms.txt.RoundTextField();
        btnAnadirElemento = new components.atoms.ImgButton();

        setBackground(Colores.TRANSPARENTE);

        pnlRiderAdd.setBackground(Colores.TRANSPARENTE);

        lblSuma.setText("¿Suma?");

        lblElemento.setText("Elemento");

        lblCantidad.setText("Cantidad");

        btnAnadirElemento.setTipo(Botones.BTN_RIDER_ADD);
        btnAnadirElemento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAnadirElementoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlRiderAddLayout = new javax.swing.GroupLayout(pnlRiderAdd);
        pnlRiderAdd.setLayout(pnlRiderAddLayout);
        pnlRiderAddLayout.setHorizontalGroup(
            pnlRiderAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRiderAddLayout.createSequentialGroup()
                .addComponent(lblElemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtElemento, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(lblCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(lblSuma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(checkSuma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btnAnadirElemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        pnlRiderAddLayout.setVerticalGroup(
            pnlRiderAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRiderAddLayout.createSequentialGroup()
                .addGroup(pnlRiderAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRiderAddLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(checkSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlRiderAddLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlRiderAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblSuma, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCantidad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtElemento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblElemento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRiderAddLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAnadirElemento, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRiderAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRiderAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnadirElementoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnadirElementoMouseClicked
        Object[] aux = new Object[3];
        if (!txtElemento.getText().equals("") && !txtCantidad.equals("")) {
            aux[0] = txtElemento.getText();
            aux[1] = Integer.parseInt(txtCantidad.getText());
            aux[2] = checkSuma.isSelected();
        }
        tblRider.getModel().addRow(aux);
        txtElemento.setText("");
        txtCantidad.setText("");
        
        if (comunes.getAvisoRider()) {
            modal.setTipo(Modal.MODAL_INFO);
            modal.setText("Para eliminar un elemento del rider, cambia la cantidad a 0.");
            modal.setOpciones(false);
            modal.showDialog();
            comunes.setAvisoRider(false);
        }
    }//GEN-LAST:event_btnAnadirElementoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private components.atoms.ImgButton btnAnadirElemento;
    private components.atoms.RoundCheckBox checkSuma;
    private components.atoms.Label lblCantidad;
    private components.atoms.Label lblElemento;
    private components.atoms.Label lblSuma;
    private javax.swing.JPanel pnlRiderAdd;
    private components.atoms.txt.RoundTextField txtCantidad;
    private components.atoms.txt.RoundTextField txtElemento;
    // End of variables declaration//GEN-END:variables
}
