package components.atoms.txt;

import POJOs.Evento;
import assets.lookandfeel.Colores;
import assets.lookandfeel.Bordes;
import assets.lookandfeel.Fuentes;
import assets.objects.Comunes;
import assets.objects.Listeners;
import components.atoms.Label;
import javax.swing.JTextField;
import javax.swing.event.DocumentListener;

/**
 *
 * @author José Francisco Blasco Jiménez
 */
public class RoundTextField extends javax.swing.JPanel {
    private boolean correcto, requerido;
    private Label label;
    private boolean fecha, resultado;
    private DocumentListener listener;
    private Listeners listeners;
    private Evento e;
    /**
     * Creates new form RoundTextField
     */
    public RoundTextField() {
        initComponents();
        txtField.getDocument().putProperty("textField", txtField);
        txtField.getDocument().putProperty("panel", this);
    }

    public void setComunes(Comunes comunes) {
        listeners = comunes.getListeners();
    }
    
    public JTextField getTextField() {
        return txtField;
    }

    public String getText() {
        return txtField.getText();
    }

    public void setText(String text) {
        txtField.setText(text);
    }

    public boolean isResultado() {
        return resultado;
    }

    public void setResultado(boolean resultado) {
        this.resultado = resultado;
    }

    public Evento getEVento() {
        return e;
    }

    public void setEvento(Evento e) {
        this.e = e;
    }
    
    public void setFecha(boolean fecha) {
        this.fecha = fecha;
    }
    
    public void setCorrecto(boolean correcto) {
        this.correcto = correcto;
        
        coloreaComponente(!correcto, true);
    }

    public void coloreaComponente(boolean resaltar, boolean coloreaTexto) {
        if (resaltar) {
            label.setForeground(Colores.NARANJA);
            pnlRound.setBorder(Bordes.NARANJA20);
            if (coloreaTexto)
                txtField.setForeground(Colores.NARANJA);
        } else {
            label.setForeground(Colores.AZUL);
            pnlRound.setBorder(Bordes.AZUL20);
            if (coloreaTexto)
                txtField.setForeground(Colores.AZUL);
            }
    }
    
    public boolean isRequerido() {
        return requerido;
    }

    public void setRequerido(boolean requerido) {
        this.requerido = requerido;
        coloreaComponente(requerido, false);
        if (fecha)
            getTextField().getDocument().addDocumentListener(listeners.getFECHA());
    }

    public Label getLabel() {
        return label;
    }

    public void setLabel(Label label) {
        this.label = label;
    }
    
    public void habilitar() {
        setEnabled(true);
        txtField.setEditable(true);
        txtField.setBackground(Colores.BLANCO);
        pnlRound.setBackground(Colores.BLANCO);
        pnlRound.setBorder(Bordes.TEXTFIELD);
    }
    
    public void deshabilitar() {
        setEnabled(false);
        txtField.setEditable(false);
        txtField.setBackground(Colores.GRISCLARO);
        pnlRound.setBackground(Colores.GRISCLARO);
        pnlRound.setBorder(Bordes.TEXTFIELD_DISABLED);
    }
    
    public void resetear() {
        txtField.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRound = new components.atoms.RoundPanel();
        txtField = new javax.swing.JTextField();

        setBackground(Colores.TRANSPARENTE);
        setPreferredSize(new java.awt.Dimension(200, 37));

        pnlRound.setBackground(new java.awt.Color(255, 255, 255));
        pnlRound.setBorder(Bordes.AZUL20);
        pnlRound.setForeground(Colores.AZUL);
        pnlRound.setFont(Fuentes.REGULAR);
        pnlRound.setRoundBottomLeft(20);
        pnlRound.setRoundBottomRight(20);
        pnlRound.setRoundTopLeft(20);
        pnlRound.setRoundTopRight(20);

        txtField.setBackground(new java.awt.Color(255, 255, 255));
        txtField.setFont(Fuentes.REGULAR);
        txtField.setForeground(Colores.AZUL);
        txtField.setBorder(null);

        javax.swing.GroupLayout pnlRoundLayout = new javax.swing.GroupLayout(pnlRound);
        pnlRound.setLayout(pnlRoundLayout);
        pnlRoundLayout.setHorizontalGroup(
            pnlRoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRoundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtField, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlRoundLayout.setVerticalGroup(
            pnlRoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRoundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtField, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRound, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRound, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private components.atoms.RoundPanel pnlRound;
    private javax.swing.JTextField txtField;
    // End of variables declaration//GEN-END:variables
}
